### ISSUE TITLE
IndentationError: unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by qrkourier** [gluster/gdeploy#203]
```
# /usr/bin/gdeploy -c gdeploy-ovirt-gluster.conf
Traceback (most recent call last):
  File "/usr/bin/gdeploy", line 5, in <module>
    pkg_resources.run_script('gdeploy==2.0.1', 'gdeploy')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/gdeploy-2.0.1-py2.7.egg/EGG-INFO/scripts/gdeploy", line 29, in <module>
    from gdeploylib import *
  File "/usr/lib/python2.7/site-packages/gdeploy-2.0.1-py2.7.egg/gdeploylib/__init__.py", line 8, in <module>
    from call_features import call_features
  File "/usr/lib/python2.7/site-packages/gdeploy-2.0.1-py2.7.egg/gdeploylib/call_features.py", line 25, in <module>
    import gdeployfeatures
  File "/usr/lib/python2.7/site-packages/gdeploy-2.0.1-py2.7.egg/gdeployfeatures/__init__.py", line 11, in <module>
    import nfs_ganesha
  File "/usr/lib/python2.7/site-packages/gdeploy-2.0.1-py2.7.egg/gdeployfeatures/nfs_ganesha/__init__.py", line 1, in <module>
    import nfs_ganesha
  File "/usr/lib/python2.7/site-packages/gdeploy-2.0.1-py2.7.egg/gdeployfeatures/nfs_ganesha/nfs_ganesha.py", line 104
    if Global.trace:
                   ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by qrkourier** [comment]
This is to mark the point in the commit log where gdeploy produced the above traceback.

```
gdeploy # git log -1
commit f51b790569017a9557114b4343c76ac73530b56c
Merge: b44b97b 85eba7d
Author: Sachidananda Urs <sacchi@gmail.com>
Date:   Wed Nov 2 08:01:02 2016 +0530

    Merge pull request #202 from gluster-deploy/master

    Fix a typo where yaml filename was missed
```

**Comment by qrkourier** [comment]
This is to mark the last commit that does _not_ result in a traceback

```
commit 5e31f793d31e0ab9602ab90cabaf58c98e4b3724
Author: Devyani Kota <divs.passion.18@gmail.com>
Date:   Wed Oct 26 19:19:30 2016 +0530

    Add logging for yum module
```

And so I suspect that the following commit #198 did introduce the problem.

**Comment by sac** [comment]
@qrkourier yep. That is ugly. I'm fixing it now.

**Comment by nigelbabu** [comment]
@sac It's probably worth spending 5 mins to write up a Travis CI job to check pyflakes (and pep8?) before merging. What do you think?

**Comment by sac** [comment]
Looks like it was always there:

commit 85eba7d35482c3ffd240bc783d95826f977201d9
Author: Sachidananda Urs sacchi@gmail.com
Date:   Wed Nov 2 07:56:59 2016 +0530

```
Fix a typo where yaml filename was missed
```

diff --git a/gdeployfeatures/ctdb/ctdb.py b/gdeployfeatures/ctdb/ctdb.py
index 5fcef96..55acbfb 100644
--- a/gdeployfeatures/ctdb/ctdb.py
+++ b/gdeployfeatures/ctdb/ctdb.py
@@ -70,5 +70,5 @@ def ctdb_setup(section_dict):
                  defaults.SMB_FOR_CTDB]
     if Global.trace:
         for ymll in yaml_list:
-            Global.logger.info("Executing %s."%)
-            Global.logger.info("Executing %s."%ymll)
   return section_dict, yaml_list

That commit does only one change. Adding ymll.
I've fixed it, pushed the changes. I'll test your config.

**Comment by sac** [comment]
@nigelbabu yep. I will do it, that's a good suggestion. It is high time we should catch these.

**Comment by sac** [comment]
This issue is fixed.
