### ISSUE TITLE
Issue while running it on mac

### ISSUE THREAD

**Issue by smitthakkar96** [gluster/gdeploy#416]
Below is the traceback of the error I am getting

``` Traceback (most recent call last):
  File "/usr/local/bin/gdeploy", line 4, in <module>
    __import__('pkg_resources').run_script('gdeploy===master', 'gdeploy')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1667, in run_script
    exec(code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/gdeploy-master-py2.7.egg/EGG-INFO/scripts/gdeploy", line 219, in <module>
    main(sys.argv[1:])
  File "/Library/Python/2.7/site-packages/gdeploy-master-py2.7.egg/EGG-INFO/scripts/gdeploy", line 201, in main
    create_files_and_dirs()
  File "/Library/Python/2.7/site-packages/gdeploy-master-py2.7.egg/EGG-INFO/scripts/gdeploy", line 151, in create_files_and_dirs
    helpers.touch_file(Global.group_file)
  File "/Library/Python/2.7/site-packages/gdeploy-master-py2.7.egg/gdeploylib/helpers.py", line 105, in touch_file
    os.mknod(filename)
OSError: [Errno 22] Invalid argument
```

**Comment by shukapoo** [comment]
Any idea how to get rid of this? I am also getting same error
